services:
    nginx:
      image: nginx:alpine
      ports:
        - "80:80"
      env_file:
        - .env
      volumes:
        - ./docker/dev/nginx/default.conf:/etc/nginx/conf.d/default.conf
        - .:/var/www/html
      depends_on:
        - php

    php:
      build:
        context: .
        dockerfile: docker/dev/Dockerfile
      env_file:
        - .env
      volumes:
        - .:/var/www/html
        - ./app:/var/www/html/app:delegated
        - ./grumphp.yml:/var/www/html/grumphp.yml:delegated
        - ./docker/php/dev/php.ini:/usr/local/etc/php/conf.d/dev.ini
      depends_on:
        - postgres

    postgres:
      image: postgres:14.15-alpine3.21
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
        POSTGRES_DB: proverbs
      env_file:
        - .env
      volumes:
        - dbase:/var/lib/postgresql/data

    redis:
      image: redis:7.4-alpine
      volumes:
        - redisdata:/data
      ports:
        - "6379:6379"

volumes:
  dbase:
  redisdata:
